name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: python -m pip install -r requirements.txt
    - name: Run unit + integration tests with coverage
      run: |
        pytest --cov=poker --cov-report=xml --cov-fail-under=75
    - name: Build sdist & wheel
      run: python -m build
