name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Setup Path
      shell: bash
      run: |
        PROJ_NEW_PATH=$(python -c "print('${{github.action_path}}'.replace('./.', '.'))")
        echo "PROJ_NEW_PATH=$PROJ_NEW_PATH" >> $GITHUB_ENV
    - run: python -m pip install -r requirements.txt
    - name: Debug directory structure
      run: |
        ls -R
    - name: Run unit + integration tests with coverage
      run: |
        python -m pytest pokergame --cov=pokergame --cov-report=xml --cov-fail-under=75
    - name: Build sdist & wheel
      run: |
        python -m build
