name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: '.'
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        cd poker-project
        python -m pip install -r requirements.txt
    - name: Run tests
      run: |
        cd poker-project
        PYTHONPATH=$PWD python -m pytest pokergame --cov=pokergame --cov-report=xml --cov-fail-under=75